#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse

import stdnum.isbn

...  # Python 3 is required

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-n', choices=('10', '13'), default='13')
    ap.add_argument('isbn', metavar='ISBN')
    options = ap.parse_args()
    n = int(options.n)
    convert = {
        10: stdnum.isbn.to_isbn10,
        13: stdnum.isbn.to_isbn13,
    }[n]
    isbn = convert(options.isbn)
    print(isbn)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
