#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import sys

import stdnum.isbn

...  # Python 3 is required

def main():
    ap = argparse.ArgumentParser()
    if sys.version_info < (3, 10):
        # https://bugs.python.org/issue9694
        ap._optionals.title = 'options'
    ap.add_argument('-n', choices=('10', '13'), default='13', help='ISBN type to convert to (default: 13)')
    ap.add_argument('-f', action='store_true', help='use standard presentation format')
    ap.add_argument('isbn', metavar='ISBN')
    options = ap.parse_args()
    n = int(options.n)
    convert = {
        10: stdnum.isbn.to_isbn10,
        13: stdnum.isbn.to_isbn13,
    }[n]
    isbn = stdnum.isbn.validate(options.isbn)
    isbn = convert(isbn)
    if options.f:
        isbn = stdnum.isbn.format(isbn)
    print(isbn)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
